/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: api/v1/data_point.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace api.v1 {
    export class DriveDataPoint extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            timestamp_unix?: number;
            available_vitals?: Map<string, boolean>;
            rpm?: number;
            speed?: number;
            throttle_position?: number;
            coolant_temp?: number;
            fuel_rate?: number;
            odometer?: number;
            engine_exhaust_flow?: number;
            fuel_tank_level?: number;
            latitude?: number;
            longitude?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("timestamp_unix" in data && data.timestamp_unix != undefined) {
                    this.timestamp_unix = data.timestamp_unix;
                }
                if ("available_vitals" in data && data.available_vitals != undefined) {
                    this.available_vitals = data.available_vitals;
                }
                if ("rpm" in data && data.rpm != undefined) {
                    this.rpm = data.rpm;
                }
                if ("speed" in data && data.speed != undefined) {
                    this.speed = data.speed;
                }
                if ("throttle_position" in data && data.throttle_position != undefined) {
                    this.throttle_position = data.throttle_position;
                }
                if ("coolant_temp" in data && data.coolant_temp != undefined) {
                    this.coolant_temp = data.coolant_temp;
                }
                if ("fuel_rate" in data && data.fuel_rate != undefined) {
                    this.fuel_rate = data.fuel_rate;
                }
                if ("odometer" in data && data.odometer != undefined) {
                    this.odometer = data.odometer;
                }
                if ("engine_exhaust_flow" in data && data.engine_exhaust_flow != undefined) {
                    this.engine_exhaust_flow = data.engine_exhaust_flow;
                }
                if ("fuel_tank_level" in data && data.fuel_tank_level != undefined) {
                    this.fuel_tank_level = data.fuel_tank_level;
                }
                if ("latitude" in data && data.latitude != undefined) {
                    this.latitude = data.latitude;
                }
                if ("longitude" in data && data.longitude != undefined) {
                    this.longitude = data.longitude;
                }
            }
            if (!this.available_vitals)
                this.available_vitals = new Map();
        }
        get timestamp_unix() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set timestamp_unix(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get available_vitals() {
            return pb_1.Message.getField(this, 2) as any as Map<string, boolean>;
        }
        set available_vitals(value: Map<string, boolean>) {
            pb_1.Message.setField(this, 2, value as any);
        }
        get rpm() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set rpm(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get speed() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set speed(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get throttle_position() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set throttle_position(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get coolant_temp() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set coolant_temp(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get fuel_rate() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set fuel_rate(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get odometer() {
            return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
        }
        set odometer(value: number) {
            pb_1.Message.setField(this, 8, value);
        }
        get engine_exhaust_flow() {
            return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
        }
        set engine_exhaust_flow(value: number) {
            pb_1.Message.setField(this, 9, value);
        }
        get fuel_tank_level() {
            return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
        }
        set fuel_tank_level(value: number) {
            pb_1.Message.setField(this, 10, value);
        }
        get latitude() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set latitude(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        get longitude() {
            return pb_1.Message.getFieldWithDefault(this, 12, 0) as number;
        }
        set longitude(value: number) {
            pb_1.Message.setField(this, 12, value);
        }
        static fromObject(data: {
            timestamp_unix?: number;
            available_vitals?: {
                [key: string]: boolean;
            };
            rpm?: number;
            speed?: number;
            throttle_position?: number;
            coolant_temp?: number;
            fuel_rate?: number;
            odometer?: number;
            engine_exhaust_flow?: number;
            fuel_tank_level?: number;
            latitude?: number;
            longitude?: number;
        }): DriveDataPoint {
            const message = new DriveDataPoint({});
            if (data.timestamp_unix != null) {
                message.timestamp_unix = data.timestamp_unix;
            }
            if (typeof data.available_vitals == "object") {
                message.available_vitals = new Map(Object.entries(data.available_vitals));
            }
            if (data.rpm != null) {
                message.rpm = data.rpm;
            }
            if (data.speed != null) {
                message.speed = data.speed;
            }
            if (data.throttle_position != null) {
                message.throttle_position = data.throttle_position;
            }
            if (data.coolant_temp != null) {
                message.coolant_temp = data.coolant_temp;
            }
            if (data.fuel_rate != null) {
                message.fuel_rate = data.fuel_rate;
            }
            if (data.odometer != null) {
                message.odometer = data.odometer;
            }
            if (data.engine_exhaust_flow != null) {
                message.engine_exhaust_flow = data.engine_exhaust_flow;
            }
            if (data.fuel_tank_level != null) {
                message.fuel_tank_level = data.fuel_tank_level;
            }
            if (data.latitude != null) {
                message.latitude = data.latitude;
            }
            if (data.longitude != null) {
                message.longitude = data.longitude;
            }
            return message;
        }
        toObject() {
            const data: {
                timestamp_unix?: number;
                available_vitals?: {
                    [key: string]: boolean;
                };
                rpm?: number;
                speed?: number;
                throttle_position?: number;
                coolant_temp?: number;
                fuel_rate?: number;
                odometer?: number;
                engine_exhaust_flow?: number;
                fuel_tank_level?: number;
                latitude?: number;
                longitude?: number;
            } = {};
            if (this.timestamp_unix != null) {
                data.timestamp_unix = this.timestamp_unix;
            }
            if (this.available_vitals != null) {
                data.available_vitals = (Object.fromEntries)(this.available_vitals);
            }
            if (this.rpm != null) {
                data.rpm = this.rpm;
            }
            if (this.speed != null) {
                data.speed = this.speed;
            }
            if (this.throttle_position != null) {
                data.throttle_position = this.throttle_position;
            }
            if (this.coolant_temp != null) {
                data.coolant_temp = this.coolant_temp;
            }
            if (this.fuel_rate != null) {
                data.fuel_rate = this.fuel_rate;
            }
            if (this.odometer != null) {
                data.odometer = this.odometer;
            }
            if (this.engine_exhaust_flow != null) {
                data.engine_exhaust_flow = this.engine_exhaust_flow;
            }
            if (this.fuel_tank_level != null) {
                data.fuel_tank_level = this.fuel_tank_level;
            }
            if (this.latitude != null) {
                data.latitude = this.latitude;
            }
            if (this.longitude != null) {
                data.longitude = this.longitude;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.timestamp_unix != 0)
                writer.writeInt32(1, this.timestamp_unix);
            for (const [key, value] of this.available_vitals) {
                writer.writeMessage(2, this.available_vitals, () => {
                    writer.writeString(1, key);
                    writer.writeBool(2, value);
                });
            }
            if (this.rpm != 0)
                writer.writeInt32(3, this.rpm);
            if (this.speed != 0)
                writer.writeInt32(4, this.speed);
            if (this.throttle_position != 0)
                writer.writeDouble(5, this.throttle_position);
            if (this.coolant_temp != 0)
                writer.writeInt32(6, this.coolant_temp);
            if (this.fuel_rate != 0)
                writer.writeDouble(7, this.fuel_rate);
            if (this.odometer != 0)
                writer.writeDouble(8, this.odometer);
            if (this.engine_exhaust_flow != 0)
                writer.writeDouble(9, this.engine_exhaust_flow);
            if (this.fuel_tank_level != 0)
                writer.writeDouble(10, this.fuel_tank_level);
            if (this.latitude != 0)
                writer.writeDouble(11, this.latitude);
            if (this.longitude != 0)
                writer.writeDouble(12, this.longitude);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DriveDataPoint {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DriveDataPoint();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.timestamp_unix = reader.readInt32();
                        break;
                    case 2:
                        reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.available_vitals as any, reader, reader.readString, reader.readBool));
                        break;
                    case 3:
                        message.rpm = reader.readInt32();
                        break;
                    case 4:
                        message.speed = reader.readInt32();
                        break;
                    case 5:
                        message.throttle_position = reader.readDouble();
                        break;
                    case 6:
                        message.coolant_temp = reader.readInt32();
                        break;
                    case 7:
                        message.fuel_rate = reader.readDouble();
                        break;
                    case 8:
                        message.odometer = reader.readDouble();
                        break;
                    case 9:
                        message.engine_exhaust_flow = reader.readDouble();
                        break;
                    case 10:
                        message.fuel_tank_level = reader.readDouble();
                        break;
                    case 11:
                        message.latitude = reader.readDouble();
                        break;
                    case 12:
                        message.longitude = reader.readDouble();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DriveDataPoint {
            return DriveDataPoint.deserialize(bytes);
        }
    }
}
