/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: api/v1/drive_data_point.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace api.v1 {
    export class DriveDataPoint extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            timestamp_unix?: number;
            rpm_available?: boolean;
            rpm?: number;
            speed_available?: boolean;
            speed?: number;
            throttle_position_available?: boolean;
            throttle_position?: number;
            coolant_temp_available?: boolean;
            coolant_temp?: number;
            fuel_rate_available?: boolean;
            fuel_rate?: number;
            odometer_available?: boolean;
            odometer?: number;
            engine_exhaust_flow_available?: boolean;
            engine_exhaust_flow?: number;
            fuel_tank_level_available?: boolean;
            fuel_tank_level?: number;
            latitude?: number;
            longitude?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("timestamp_unix" in data && data.timestamp_unix != undefined) {
                    this.timestamp_unix = data.timestamp_unix;
                }
                if ("rpm_available" in data && data.rpm_available != undefined) {
                    this.rpm_available = data.rpm_available;
                }
                if ("rpm" in data && data.rpm != undefined) {
                    this.rpm = data.rpm;
                }
                if ("speed_available" in data && data.speed_available != undefined) {
                    this.speed_available = data.speed_available;
                }
                if ("speed" in data && data.speed != undefined) {
                    this.speed = data.speed;
                }
                if ("throttle_position_available" in data && data.throttle_position_available != undefined) {
                    this.throttle_position_available = data.throttle_position_available;
                }
                if ("throttle_position" in data && data.throttle_position != undefined) {
                    this.throttle_position = data.throttle_position;
                }
                if ("coolant_temp_available" in data && data.coolant_temp_available != undefined) {
                    this.coolant_temp_available = data.coolant_temp_available;
                }
                if ("coolant_temp" in data && data.coolant_temp != undefined) {
                    this.coolant_temp = data.coolant_temp;
                }
                if ("fuel_rate_available" in data && data.fuel_rate_available != undefined) {
                    this.fuel_rate_available = data.fuel_rate_available;
                }
                if ("fuel_rate" in data && data.fuel_rate != undefined) {
                    this.fuel_rate = data.fuel_rate;
                }
                if ("odometer_available" in data && data.odometer_available != undefined) {
                    this.odometer_available = data.odometer_available;
                }
                if ("odometer" in data && data.odometer != undefined) {
                    this.odometer = data.odometer;
                }
                if ("engine_exhaust_flow_available" in data && data.engine_exhaust_flow_available != undefined) {
                    this.engine_exhaust_flow_available = data.engine_exhaust_flow_available;
                }
                if ("engine_exhaust_flow" in data && data.engine_exhaust_flow != undefined) {
                    this.engine_exhaust_flow = data.engine_exhaust_flow;
                }
                if ("fuel_tank_level_available" in data && data.fuel_tank_level_available != undefined) {
                    this.fuel_tank_level_available = data.fuel_tank_level_available;
                }
                if ("fuel_tank_level" in data && data.fuel_tank_level != undefined) {
                    this.fuel_tank_level = data.fuel_tank_level;
                }
                if ("latitude" in data && data.latitude != undefined) {
                    this.latitude = data.latitude;
                }
                if ("longitude" in data && data.longitude != undefined) {
                    this.longitude = data.longitude;
                }
            }
        }
        get timestamp_unix() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set timestamp_unix(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get rpm_available() {
            return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
        }
        set rpm_available(value: boolean) {
            pb_1.Message.setField(this, 2, value);
        }
        get rpm() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set rpm(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get speed_available() {
            return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
        }
        set speed_available(value: boolean) {
            pb_1.Message.setField(this, 4, value);
        }
        get speed() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set speed(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get throttle_position_available() {
            return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
        }
        set throttle_position_available(value: boolean) {
            pb_1.Message.setField(this, 6, value);
        }
        get throttle_position() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set throttle_position(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get coolant_temp_available() {
            return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
        }
        set coolant_temp_available(value: boolean) {
            pb_1.Message.setField(this, 8, value);
        }
        get coolant_temp() {
            return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
        }
        set coolant_temp(value: number) {
            pb_1.Message.setField(this, 9, value);
        }
        get fuel_rate_available() {
            return pb_1.Message.getFieldWithDefault(this, 10, false) as boolean;
        }
        set fuel_rate_available(value: boolean) {
            pb_1.Message.setField(this, 10, value);
        }
        get fuel_rate() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set fuel_rate(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        get odometer_available() {
            return pb_1.Message.getFieldWithDefault(this, 12, false) as boolean;
        }
        set odometer_available(value: boolean) {
            pb_1.Message.setField(this, 12, value);
        }
        get odometer() {
            return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
        }
        set odometer(value: number) {
            pb_1.Message.setField(this, 13, value);
        }
        get engine_exhaust_flow_available() {
            return pb_1.Message.getFieldWithDefault(this, 14, false) as boolean;
        }
        set engine_exhaust_flow_available(value: boolean) {
            pb_1.Message.setField(this, 14, value);
        }
        get engine_exhaust_flow() {
            return pb_1.Message.getFieldWithDefault(this, 15, 0) as number;
        }
        set engine_exhaust_flow(value: number) {
            pb_1.Message.setField(this, 15, value);
        }
        get fuel_tank_level_available() {
            return pb_1.Message.getFieldWithDefault(this, 16, false) as boolean;
        }
        set fuel_tank_level_available(value: boolean) {
            pb_1.Message.setField(this, 16, value);
        }
        get fuel_tank_level() {
            return pb_1.Message.getFieldWithDefault(this, 17, 0) as number;
        }
        set fuel_tank_level(value: number) {
            pb_1.Message.setField(this, 17, value);
        }
        get latitude() {
            return pb_1.Message.getFieldWithDefault(this, 18, 0) as number;
        }
        set latitude(value: number) {
            pb_1.Message.setField(this, 18, value);
        }
        get longitude() {
            return pb_1.Message.getFieldWithDefault(this, 19, 0) as number;
        }
        set longitude(value: number) {
            pb_1.Message.setField(this, 19, value);
        }
        static fromObject(data: {
            timestamp_unix?: number;
            rpm_available?: boolean;
            rpm?: number;
            speed_available?: boolean;
            speed?: number;
            throttle_position_available?: boolean;
            throttle_position?: number;
            coolant_temp_available?: boolean;
            coolant_temp?: number;
            fuel_rate_available?: boolean;
            fuel_rate?: number;
            odometer_available?: boolean;
            odometer?: number;
            engine_exhaust_flow_available?: boolean;
            engine_exhaust_flow?: number;
            fuel_tank_level_available?: boolean;
            fuel_tank_level?: number;
            latitude?: number;
            longitude?: number;
        }): DriveDataPoint {
            const message = new DriveDataPoint({});
            if (data.timestamp_unix != null) {
                message.timestamp_unix = data.timestamp_unix;
            }
            if (data.rpm_available != null) {
                message.rpm_available = data.rpm_available;
            }
            if (data.rpm != null) {
                message.rpm = data.rpm;
            }
            if (data.speed_available != null) {
                message.speed_available = data.speed_available;
            }
            if (data.speed != null) {
                message.speed = data.speed;
            }
            if (data.throttle_position_available != null) {
                message.throttle_position_available = data.throttle_position_available;
            }
            if (data.throttle_position != null) {
                message.throttle_position = data.throttle_position;
            }
            if (data.coolant_temp_available != null) {
                message.coolant_temp_available = data.coolant_temp_available;
            }
            if (data.coolant_temp != null) {
                message.coolant_temp = data.coolant_temp;
            }
            if (data.fuel_rate_available != null) {
                message.fuel_rate_available = data.fuel_rate_available;
            }
            if (data.fuel_rate != null) {
                message.fuel_rate = data.fuel_rate;
            }
            if (data.odometer_available != null) {
                message.odometer_available = data.odometer_available;
            }
            if (data.odometer != null) {
                message.odometer = data.odometer;
            }
            if (data.engine_exhaust_flow_available != null) {
                message.engine_exhaust_flow_available = data.engine_exhaust_flow_available;
            }
            if (data.engine_exhaust_flow != null) {
                message.engine_exhaust_flow = data.engine_exhaust_flow;
            }
            if (data.fuel_tank_level_available != null) {
                message.fuel_tank_level_available = data.fuel_tank_level_available;
            }
            if (data.fuel_tank_level != null) {
                message.fuel_tank_level = data.fuel_tank_level;
            }
            if (data.latitude != null) {
                message.latitude = data.latitude;
            }
            if (data.longitude != null) {
                message.longitude = data.longitude;
            }
            return message;
        }
        toObject() {
            const data: {
                timestamp_unix?: number;
                rpm_available?: boolean;
                rpm?: number;
                speed_available?: boolean;
                speed?: number;
                throttle_position_available?: boolean;
                throttle_position?: number;
                coolant_temp_available?: boolean;
                coolant_temp?: number;
                fuel_rate_available?: boolean;
                fuel_rate?: number;
                odometer_available?: boolean;
                odometer?: number;
                engine_exhaust_flow_available?: boolean;
                engine_exhaust_flow?: number;
                fuel_tank_level_available?: boolean;
                fuel_tank_level?: number;
                latitude?: number;
                longitude?: number;
            } = {};
            if (this.timestamp_unix != null) {
                data.timestamp_unix = this.timestamp_unix;
            }
            if (this.rpm_available != null) {
                data.rpm_available = this.rpm_available;
            }
            if (this.rpm != null) {
                data.rpm = this.rpm;
            }
            if (this.speed_available != null) {
                data.speed_available = this.speed_available;
            }
            if (this.speed != null) {
                data.speed = this.speed;
            }
            if (this.throttle_position_available != null) {
                data.throttle_position_available = this.throttle_position_available;
            }
            if (this.throttle_position != null) {
                data.throttle_position = this.throttle_position;
            }
            if (this.coolant_temp_available != null) {
                data.coolant_temp_available = this.coolant_temp_available;
            }
            if (this.coolant_temp != null) {
                data.coolant_temp = this.coolant_temp;
            }
            if (this.fuel_rate_available != null) {
                data.fuel_rate_available = this.fuel_rate_available;
            }
            if (this.fuel_rate != null) {
                data.fuel_rate = this.fuel_rate;
            }
            if (this.odometer_available != null) {
                data.odometer_available = this.odometer_available;
            }
            if (this.odometer != null) {
                data.odometer = this.odometer;
            }
            if (this.engine_exhaust_flow_available != null) {
                data.engine_exhaust_flow_available = this.engine_exhaust_flow_available;
            }
            if (this.engine_exhaust_flow != null) {
                data.engine_exhaust_flow = this.engine_exhaust_flow;
            }
            if (this.fuel_tank_level_available != null) {
                data.fuel_tank_level_available = this.fuel_tank_level_available;
            }
            if (this.fuel_tank_level != null) {
                data.fuel_tank_level = this.fuel_tank_level;
            }
            if (this.latitude != null) {
                data.latitude = this.latitude;
            }
            if (this.longitude != null) {
                data.longitude = this.longitude;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.timestamp_unix != 0)
                writer.writeInt64(1, this.timestamp_unix);
            if (this.rpm_available != false)
                writer.writeBool(2, this.rpm_available);
            if (this.rpm != 0)
                writer.writeInt32(3, this.rpm);
            if (this.speed_available != false)
                writer.writeBool(4, this.speed_available);
            if (this.speed != 0)
                writer.writeInt32(5, this.speed);
            if (this.throttle_position_available != false)
                writer.writeBool(6, this.throttle_position_available);
            if (this.throttle_position != 0)
                writer.writeDouble(7, this.throttle_position);
            if (this.coolant_temp_available != false)
                writer.writeBool(8, this.coolant_temp_available);
            if (this.coolant_temp != 0)
                writer.writeInt32(9, this.coolant_temp);
            if (this.fuel_rate_available != false)
                writer.writeBool(10, this.fuel_rate_available);
            if (this.fuel_rate != 0)
                writer.writeDouble(11, this.fuel_rate);
            if (this.odometer_available != false)
                writer.writeBool(12, this.odometer_available);
            if (this.odometer != 0)
                writer.writeDouble(13, this.odometer);
            if (this.engine_exhaust_flow_available != false)
                writer.writeBool(14, this.engine_exhaust_flow_available);
            if (this.engine_exhaust_flow != 0)
                writer.writeDouble(15, this.engine_exhaust_flow);
            if (this.fuel_tank_level_available != false)
                writer.writeBool(16, this.fuel_tank_level_available);
            if (this.fuel_tank_level != 0)
                writer.writeDouble(17, this.fuel_tank_level);
            if (this.latitude != 0)
                writer.writeDouble(18, this.latitude);
            if (this.longitude != 0)
                writer.writeDouble(19, this.longitude);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DriveDataPoint {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DriveDataPoint();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.timestamp_unix = reader.readInt64();
                        break;
                    case 2:
                        message.rpm_available = reader.readBool();
                        break;
                    case 3:
                        message.rpm = reader.readInt32();
                        break;
                    case 4:
                        message.speed_available = reader.readBool();
                        break;
                    case 5:
                        message.speed = reader.readInt32();
                        break;
                    case 6:
                        message.throttle_position_available = reader.readBool();
                        break;
                    case 7:
                        message.throttle_position = reader.readDouble();
                        break;
                    case 8:
                        message.coolant_temp_available = reader.readBool();
                        break;
                    case 9:
                        message.coolant_temp = reader.readInt32();
                        break;
                    case 10:
                        message.fuel_rate_available = reader.readBool();
                        break;
                    case 11:
                        message.fuel_rate = reader.readDouble();
                        break;
                    case 12:
                        message.odometer_available = reader.readBool();
                        break;
                    case 13:
                        message.odometer = reader.readDouble();
                        break;
                    case 14:
                        message.engine_exhaust_flow_available = reader.readBool();
                        break;
                    case 15:
                        message.engine_exhaust_flow = reader.readDouble();
                        break;
                    case 16:
                        message.fuel_tank_level_available = reader.readBool();
                        break;
                    case 17:
                        message.fuel_tank_level = reader.readDouble();
                        break;
                    case 18:
                        message.latitude = reader.readDouble();
                        break;
                    case 19:
                        message.longitude = reader.readDouble();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DriveDataPoint {
            return DriveDataPoint.deserialize(bytes);
        }
    }
}
