/**
 * @fileoverview gRPC-Web generated client stub for colombo.api.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: api/v1/service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as common_types_pb from '../../common/types_pb'; // proto import: "common/types.proto"


export class TelemetryServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendReadings = new grpcWeb.MethodDescriptor(
    '/colombo.api.v1.TelemetryService/SendReadings',
    grpcWeb.MethodType.UNARY,
    common_types_pb.TelemetryBatchRequest,
    common_types_pb.TelemetryResponse,
    (request: common_types_pb.TelemetryBatchRequest) => {
      return request.serializeBinary();
    },
    common_types_pb.TelemetryResponse.deserializeBinary
  );

  sendReadings(
    request: common_types_pb.TelemetryBatchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<common_types_pb.TelemetryResponse>;

  sendReadings(
    request: common_types_pb.TelemetryBatchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: common_types_pb.TelemetryResponse) => void): grpcWeb.ClientReadableStream<common_types_pb.TelemetryResponse>;

  sendReadings(
    request: common_types_pb.TelemetryBatchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: common_types_pb.TelemetryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/colombo.api.v1.TelemetryService/SendReadings',
        request,
        metadata || {},
        this.methodDescriptorSendReadings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/colombo.api.v1.TelemetryService/SendReadings',
    request,
    metadata || {},
    this.methodDescriptorSendReadings);
  }

}

