/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: api/v1/service.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./..\\..\\common\\types";
import * as grpc_1 from "@grpc/grpc-js";
export namespace colombo.api.v1 {
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedTelemetryServiceService {
        static definition = {
            SendReadings: {
                path: "/colombo.api.v1.TelemetryService/SendReadings",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.colombo.common.TelemetryBatchRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.colombo.common.TelemetryBatchRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.colombo.common.TelemetryResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.colombo.common.TelemetryResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract SendReadings(call: grpc_1.ServerUnaryCall<dependency_1.colombo.common.TelemetryBatchRequest, dependency_1.colombo.common.TelemetryResponse>, callback: grpc_1.sendUnaryData<dependency_1.colombo.common.TelemetryResponse>): void;
    }
    export class TelemetryServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedTelemetryServiceService.definition, "TelemetryService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        SendReadings: GrpcUnaryServiceInterface<dependency_1.colombo.common.TelemetryBatchRequest, dependency_1.colombo.common.TelemetryResponse> = (message: dependency_1.colombo.common.TelemetryBatchRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.colombo.common.TelemetryResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.colombo.common.TelemetryResponse>, callback?: grpc_1.requestCallback<dependency_1.colombo.common.TelemetryResponse>): grpc_1.ClientUnaryCall => {
            return super.SendReadings(message, metadata, options, callback);
        };
    }
}
