/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: common/types.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./..\\google\\protobuf\\timestamp";
import * as pb_1 from "google-protobuf";
export namespace colombo.common {
    export class TelemetryReading extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            timestamp?: dependency_1.google.protobuf.Timestamp;
            latitude?: number;
            longitude?: number;
            rpm?: number;
            speed?: number;
            throttle_position?: number;
            coolant_temp?: number;
            fuel_rate?: number;
            odometer?: number;
            engine_exhaust_flow?: number;
            fuel_tank_level?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("timestamp" in data && data.timestamp != undefined) {
                    this.timestamp = data.timestamp;
                }
                if ("latitude" in data && data.latitude != undefined) {
                    this.latitude = data.latitude;
                }
                if ("longitude" in data && data.longitude != undefined) {
                    this.longitude = data.longitude;
                }
                if ("rpm" in data && data.rpm != undefined) {
                    this.rpm = data.rpm;
                }
                if ("speed" in data && data.speed != undefined) {
                    this.speed = data.speed;
                }
                if ("throttle_position" in data && data.throttle_position != undefined) {
                    this.throttle_position = data.throttle_position;
                }
                if ("coolant_temp" in data && data.coolant_temp != undefined) {
                    this.coolant_temp = data.coolant_temp;
                }
                if ("fuel_rate" in data && data.fuel_rate != undefined) {
                    this.fuel_rate = data.fuel_rate;
                }
                if ("odometer" in data && data.odometer != undefined) {
                    this.odometer = data.odometer;
                }
                if ("engine_exhaust_flow" in data && data.engine_exhaust_flow != undefined) {
                    this.engine_exhaust_flow = data.engine_exhaust_flow;
                }
                if ("fuel_tank_level" in data && data.fuel_tank_level != undefined) {
                    this.fuel_tank_level = data.fuel_tank_level;
                }
            }
        }
        get timestamp() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 1) as dependency_1.google.protobuf.Timestamp;
        }
        set timestamp(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_timestamp() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get latitude() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set latitude(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get longitude() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set longitude(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get rpm() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set rpm(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get speed() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set speed(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get throttle_position() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set throttle_position(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get coolant_temp() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set coolant_temp(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get fuel_rate() {
            return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
        }
        set fuel_rate(value: number) {
            pb_1.Message.setField(this, 8, value);
        }
        get odometer() {
            return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
        }
        set odometer(value: number) {
            pb_1.Message.setField(this, 9, value);
        }
        get engine_exhaust_flow() {
            return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
        }
        set engine_exhaust_flow(value: number) {
            pb_1.Message.setField(this, 10, value);
        }
        get fuel_tank_level() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set fuel_tank_level(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        static fromObject(data: {
            timestamp?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            latitude?: number;
            longitude?: number;
            rpm?: number;
            speed?: number;
            throttle_position?: number;
            coolant_temp?: number;
            fuel_rate?: number;
            odometer?: number;
            engine_exhaust_flow?: number;
            fuel_tank_level?: number;
        }): TelemetryReading {
            const message = new TelemetryReading({});
            if (data.timestamp != null) {
                message.timestamp = dependency_1.google.protobuf.Timestamp.fromObject(data.timestamp);
            }
            if (data.latitude != null) {
                message.latitude = data.latitude;
            }
            if (data.longitude != null) {
                message.longitude = data.longitude;
            }
            if (data.rpm != null) {
                message.rpm = data.rpm;
            }
            if (data.speed != null) {
                message.speed = data.speed;
            }
            if (data.throttle_position != null) {
                message.throttle_position = data.throttle_position;
            }
            if (data.coolant_temp != null) {
                message.coolant_temp = data.coolant_temp;
            }
            if (data.fuel_rate != null) {
                message.fuel_rate = data.fuel_rate;
            }
            if (data.odometer != null) {
                message.odometer = data.odometer;
            }
            if (data.engine_exhaust_flow != null) {
                message.engine_exhaust_flow = data.engine_exhaust_flow;
            }
            if (data.fuel_tank_level != null) {
                message.fuel_tank_level = data.fuel_tank_level;
            }
            return message;
        }
        toObject() {
            const data: {
                timestamp?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                latitude?: number;
                longitude?: number;
                rpm?: number;
                speed?: number;
                throttle_position?: number;
                coolant_temp?: number;
                fuel_rate?: number;
                odometer?: number;
                engine_exhaust_flow?: number;
                fuel_tank_level?: number;
            } = {};
            if (this.timestamp != null) {
                data.timestamp = this.timestamp.toObject();
            }
            if (this.latitude != null) {
                data.latitude = this.latitude;
            }
            if (this.longitude != null) {
                data.longitude = this.longitude;
            }
            if (this.rpm != null) {
                data.rpm = this.rpm;
            }
            if (this.speed != null) {
                data.speed = this.speed;
            }
            if (this.throttle_position != null) {
                data.throttle_position = this.throttle_position;
            }
            if (this.coolant_temp != null) {
                data.coolant_temp = this.coolant_temp;
            }
            if (this.fuel_rate != null) {
                data.fuel_rate = this.fuel_rate;
            }
            if (this.odometer != null) {
                data.odometer = this.odometer;
            }
            if (this.engine_exhaust_flow != null) {
                data.engine_exhaust_flow = this.engine_exhaust_flow;
            }
            if (this.fuel_tank_level != null) {
                data.fuel_tank_level = this.fuel_tank_level;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_timestamp)
                writer.writeMessage(1, this.timestamp, () => this.timestamp.serialize(writer));
            if (this.latitude != 0)
                writer.writeDouble(2, this.latitude);
            if (this.longitude != 0)
                writer.writeDouble(3, this.longitude);
            if (this.rpm != 0)
                writer.writeInt32(4, this.rpm);
            if (this.speed != 0)
                writer.writeInt32(5, this.speed);
            if (this.throttle_position != 0)
                writer.writeFloat(6, this.throttle_position);
            if (this.coolant_temp != 0)
                writer.writeInt32(7, this.coolant_temp);
            if (this.fuel_rate != 0)
                writer.writeFloat(8, this.fuel_rate);
            if (this.odometer != 0)
                writer.writeDouble(9, this.odometer);
            if (this.engine_exhaust_flow != 0)
                writer.writeFloat(10, this.engine_exhaust_flow);
            if (this.fuel_tank_level != 0)
                writer.writeFloat(11, this.fuel_tank_level);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TelemetryReading {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TelemetryReading();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.timestamp, () => message.timestamp = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 2:
                        message.latitude = reader.readDouble();
                        break;
                    case 3:
                        message.longitude = reader.readDouble();
                        break;
                    case 4:
                        message.rpm = reader.readInt32();
                        break;
                    case 5:
                        message.speed = reader.readInt32();
                        break;
                    case 6:
                        message.throttle_position = reader.readFloat();
                        break;
                    case 7:
                        message.coolant_temp = reader.readInt32();
                        break;
                    case 8:
                        message.fuel_rate = reader.readFloat();
                        break;
                    case 9:
                        message.odometer = reader.readDouble();
                        break;
                    case 10:
                        message.engine_exhaust_flow = reader.readFloat();
                        break;
                    case 11:
                        message.fuel_tank_level = reader.readFloat();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TelemetryReading {
            return TelemetryReading.deserialize(bytes);
        }
    }
    export class TelemetryBatchRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            session_id?: number;
            readings?: TelemetryReading[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("session_id" in data && data.session_id != undefined) {
                    this.session_id = data.session_id;
                }
                if ("readings" in data && data.readings != undefined) {
                    this.readings = data.readings;
                }
            }
        }
        get session_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set session_id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get readings() {
            return pb_1.Message.getRepeatedWrapperField(this, TelemetryReading, 2) as TelemetryReading[];
        }
        set readings(value: TelemetryReading[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            session_id?: number;
            readings?: ReturnType<typeof TelemetryReading.prototype.toObject>[];
        }): TelemetryBatchRequest {
            const message = new TelemetryBatchRequest({});
            if (data.session_id != null) {
                message.session_id = data.session_id;
            }
            if (data.readings != null) {
                message.readings = data.readings.map(item => TelemetryReading.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                session_id?: number;
                readings?: ReturnType<typeof TelemetryReading.prototype.toObject>[];
            } = {};
            if (this.session_id != null) {
                data.session_id = this.session_id;
            }
            if (this.readings != null) {
                data.readings = this.readings.map((item: TelemetryReading) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.session_id != 0)
                writer.writeInt32(1, this.session_id);
            if (this.readings.length)
                writer.writeRepeatedMessage(2, this.readings, (item: TelemetryReading) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TelemetryBatchRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TelemetryBatchRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.session_id = reader.readInt32();
                        break;
                    case 2:
                        reader.readMessage(message.readings, () => pb_1.Message.addToRepeatedWrapperField(message, 2, TelemetryReading.deserialize(reader), TelemetryReading));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TelemetryBatchRequest {
            return TelemetryBatchRequest.deserialize(bytes);
        }
    }
    export class TelemetryResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            success?: boolean;
            message?: string;
            readings_processed?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
                if ("readings_processed" in data && data.readings_processed != undefined) {
                    this.readings_processed = data.readings_processed;
                }
            }
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get readings_processed() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set readings_processed(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            success?: boolean;
            message?: string;
            readings_processed?: number;
        }): TelemetryResponse {
            const message = new TelemetryResponse({});
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            if (data.readings_processed != null) {
                message.readings_processed = data.readings_processed;
            }
            return message;
        }
        toObject() {
            const data: {
                success?: boolean;
                message?: string;
                readings_processed?: number;
            } = {};
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            if (this.readings_processed != null) {
                data.readings_processed = this.readings_processed;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.success != false)
                writer.writeBool(1, this.success);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (this.readings_processed != 0)
                writer.writeInt32(3, this.readings_processed);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TelemetryResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TelemetryResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.success = reader.readBool();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    case 3:
                        message.readings_processed = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TelemetryResponse {
            return TelemetryResponse.deserialize(bytes);
        }
    }
}
